# See: https://taskfile.dev/api/

version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I protos/proto/distributedStorage protos/proto/distributedStorage/*.proto --go_out=./protos/gen/go/distributedStorage --go_opt=paths=source_relative --go-grpc_out=./protos/gen/go/distributedStorage --go-grpc_opt=paths=source_relative
