# See: https://taskfile.dev/api/

version: "3"

tasks:
  generate:
    aliases:
      - gen
    desc: "Generate code from proto files"
    cmds:
      - protoc -I protos/proto/distributedStorage protos/proto/distributedStorage/*.proto --go_out=./protos/gen/go/distributedStorage --go_opt=paths=source_relative --go-grpc_out=./protos/gen/go/distributedStorage --go-grpc_opt=paths=source_relative

  generate-backends:
    aliases:
      - gen-backends
    desc: "Generate code from proto files"
    cmds:
      - protoc -I protos/proto/backend backend.proto --go_out=./protos/gen/go/backend --go_opt=paths=source_relative --go-grpc_out=./protos/gen/go/backend --go-grpc_opt=paths=source_relative
  lint:
    aliases:
      - lint
    desc: "Lint code"
    cmds:
      - golangci-lint run ./...  -c .golangci-lint.yml

  migrate-new:
    desc: Create a new migration file
    cmds:
      - source .env && dbmate -u "$DBMATE_DATABASE_URL" create
      - dbmate new meta

  migrate-up:
    aliases:
      - migrate up
    desc: "Migrate database up"
    cmds:
      - source .env && dbmate --url "$DBMATE_DATABASE_URL" up

  migrate-down:
    aliases:
      - migrate down
    desc: "Migrate database down"
    cmds:
      - go run ./cmd/migrator --migrations-path=./migrations -down